spring:
  application:
    name: XSD Compare

logging:
  level:
    org.springframework: WARN
    com.compare.xsd: INFO
  file:
    clean-history-on-start: true
    name: '${app.dir}/logs/xsd-compare.log'
    max-size: 25MB
    total-size-cap: 100MB
